
/* ==================================================================
   20. GAZETECILIK ISLERI - mertseven.com/digijournalism katalogundan
   Her kayit: [baslik, kurum, bolum, adres, erisim, tespit edilen kutuphaneler]
   erisim: CANLI = dogrudan aciliyor - ENGELLI = site otomatik erisimi
   engelliyor (NYT, Bloomberg, Washington Post); tarayicida acilir.
   Olu baglantilar (6 adet) kataloga alinmadi.
   Kutuphaneler tahmin degil: sayfa kaynaginda imza aranarak bulundu.
   Ucuncu taraf betiklerden gelen yanlis eslesme olabilir.
================================================================== */
const PSECT = {
  "maps": {label:"Haritalar", wing:"geo", note:"Koordinati piksele ceviren isler: secim haritalari, akis, mekansal analiz."},
  "storytelling": {label:"Hikâye Anlatımı", wing:"story", note:"Okuma sirasini tasarlayan isler: kaydirmali anlati, uzun form."},
  "immersive": {label:"Sürükleyici", wing:"3d", note:"Derinlik, kamera ve mekan duygusu kuran isler."},
  "interactives": {label:"Oynanabilirler", wing:"game", note:"Okurun oynadigi isler: quiz, tahmin, yaris, cizdirme."},
  "visualizations": {label:"Görselleştirmeler", wing:"viz", note:"Sayiyi isarete baglayan isler: grafik, ag, karsilastirma."},
  "investigations": {label:"Araştırmalar", wing:"viz", note:"Veriyle kurulmus arastirma dosyalari ve veritabanlari."},
  "drone": {label:"Drone & Uydu", wing:"geo", note:"Yukaridan bakis: uydu goruntusu, hava cekimi, arazi degisimi."},
  "portfolios": {label:"Okuma Odası", wing:"tools", note:"Ekipler, studyolar ve derlemeler - tek tek is degil, kaynak."}
};

const PROJECTS_RAW = [
["Europakarte","Berliner Morgenpost","maps","http://interaktiv.morgenpost.de/europakarte/","CANLI",[]],
["Spies in the skies","Buzzfeed","maps","https://www.buzzfeed.com/peteraldhous/spies-in-the-skies","CANLI",[]],
["Brexit full results and analysis","The Guardian","maps","https://www.theguardian.com/politics/ng-interactive/2016/jun/23/eu-referendum-live-results-and-analysis","CANLI",[]],
["Where can you afford to buy a house","The Guardian","maps","https://www.theguardian.com/society/ng-interactive/2015/sep/02/unaffordable-country-where-can-you-afford-to-buy-a-house","CANLI",[]],
["Shipmap","Kiln","maps","http://shipmap.org/","CANLI",["Leaflet"]],
["Every Kobe Shot Ever","LA Times","maps","http://graphics.latimes.com/kobe-every-shot-ever/","CANLI",["Leaflet","Carto"]],
["Who gives money to Bernie Sanders?","LA Times","maps","http://www.latimes.com/projects/la-na-pol-sanders-donors/","CANLI",["Carto"]],
["The Best and Worst places to grow up","New York Times","maps","http://www.nytimes.com/interactive/2015/05/03/upshot/the-best-and-worst-places-to-grow-up-how-your-area-compares.html","ENGELLI",[]],
["How North Carolina Voted","New York Times","maps","http://www.nytimes.com/interactive/2016/11/08/us/elections/north-carolina-presidential-election-precinct-maps.html","ENGELLI",[]],
["How Trump Reshaped the Election Map","New York Times","maps","http://www.nytimes.com/interactive/2016/11/08/us/elections/how-trump-pushed-the-election-map-to-the-right.html","ENGELLI",[]],
["Mapping Segregation","New York Times","maps","http://www.nytimes.com/interactive/2015/07/08/us/census-race-map.html","ENGELLI",[]],
["Inside Raqqa","New York Times","maps","http://www.nytimes.com/interactive/2015/11/21/world/middleeast/inside-raqqa-capital-of-isis.html","ENGELLI",[]],
["Así se ha desplomado el PSE","Politibot","maps","https://politibot.es/interactivo/caida-pse-pais-vasco-25s/","CANLI",[]],
["The shape of slavery","Pudding","maps","https://pudding.cool/2017/01/shape-of-slavery/","CANLI",["D3.js"]],
["Hate Map","SPLC","maps","https://www.splcenter.org/hate-map","CANLI",[]],
["How Trump Redrew the Electoral Map","Washington Post","maps","https://www.washingtonpost.com/graphics/politics/2016-election/election-results-from-coast-to-coast/","ENGELLI",[]],
["A nation divided","Zeit Online","maps","http://www.zeit.de/feature/mauerfall-das-geteilte-land","CANLI",["Scrollama"]],
["M29","Berliner Morgenpost","storytelling","http://interaktiv.morgenpost.de/m29/","CANLI",[]],
["What's causing global warming","Bloomberg","storytelling","http://www.bloomberg.com/graphics/2015-whats-warming-the-world/","ENGELLI",[]],
["Dyslexia","","storytelling","http://geon.github.io/programming/2016/03/03/dsxyliea","CANLI",[]],
["Gun Deaths","FiveThirtyEight","storytelling","http://fivethirtyeight.com/features/gun-deaths/","CANLI",[]],
["Poor Millennials","","storytelling","http://highline.huffingtonpost.com/articles/en/poor-millennials/","CANLI",["Three.js"]],
["MUAC","National Geographic","storytelling","https://www.lucasinfografia.com/MUAC","CANLI",[]],
["Michael Phelps vs. Himself","New York Times","storytelling","http://www.nytimes.com/interactive/2016/08/09/sports/olympics/2016-08-09-olympics-phelps-vs-phelps.html","ENGELLI",[]],
["Snowfall","New York Times","storytelling","http://www.nytimes.com/projects/2012/snow-fall/","CANLI",[]],
["Out of Sight, out of Mind","Pitch Interactive","storytelling","http://drones.pitchinteractive.com/","CANLI",["D3.js","GSAP"]],
["Usain Bolt Replay","The Guardian","storytelling","https://www.theguardian.com/sport/ng-interactive/2016/aug/20/how-usain-bolt-secured-the-triple-treble-with-jamaica-in-the-4x100m","CANLI",[]],
["Donald Trump's first 100 days","The Guardian","storytelling","https://www.theguardian.com/us-news/ng-interactive/2017/jan/20/donald-trump-first-100-days-president-daily-updates","CANLI",[]],
["NSA files: Decoded","The Guardian","storytelling","https://www.theguardian.com/world/interactive/2013/nov/01/snowden-nsa-files-surveillance-revelations-decoded","CANLI",["Video.js"]],
["Blue Feed, Red Feed","Wall Street Journal","storytelling","http://graphics.wsj.com/blue-feed-red-feed/","CANLI",[]],
["Raising Barriers","Washington Post","storytelling","https://www.washingtonpost.com/graphics/world/border-barriers/global-illegal-immigration-prevention/","ENGELLI",[]],
["Map of the internet","Quartz","storytelling","http://qz.com/se/map-of-the-internet/","CANLI",[]],
["The New New York Skyline","National Geographic","immersive","http://www.nationalgeographic.com/new-york-city-skyline-tallest-midtown-manhattan/","CANLI",["Video.js"]],
["3D Yield Curve","New York Times","immersive","http://www.nytimes.com/interactive/2015/03/19/upshot/3d-yield-curve-economic-growth.html","ENGELLI",[]],
["Dear Architects: Sound Matters","New York Times","immersive","http://www.nytimes.com/interactive/2015/12/29/arts/design/sound-architecture.html","ENGELLI",[]],
["Reshaping New York","New York Times","immersive","http://www.nytimes.com/newsgraphics/2013/08/18/reshaping-new-york/","CANLI",[]],
["The Dawn Wall","New York Times","immersive","http://www.nytimes.com/interactive/2015/01/09/sports/the-dawn-wall-el-capitan.html","ENGELLI",[]],
["New York Times VR App","","immersive","http://www.nytimes.com/marketing/nytvr/","CANLI",[]],
["Homan Square","The Guardian","immersive","https://www.theguardian.com/us-news/ng-interactive/2015/oct/19/homan-square-chicago-police-detainees","CANLI",[]],
["Solitary Confinement","The Guardian","immersive","https://www.theguardian.com/world/ng-interactive/2016/apr/27/6x9-a-virtual-experience-of-solitary-confinement","CANLI",[]],
["The London Skyline of Tomorrow","The Guardian","immersive","https://www.theguardian.com/artanddesign/2015/dec/11/city-of-london-skyline-of-tomorrow-interactive","CANLI",[]],
["Is the Nasdaq in another Bubble?","Wall Street Journal","immersive","http://graphics.wsj.com/3d-nasdaq/","CANLI",["D3.js","Three.js"]],
["What is Code?","Bloomberg","interactives","http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/","ENGELLI",[]],
["How the Internet talks","FiveThirtyEight","interactives","http://projects.fivethirtyeight.com/reddit-ngram/","CANLI",[]],
["Trump Connections","Kim Albrecht","interactives","http://trump.kimalbrecht.com/network/","CANLI",["D3.js"]],
["Can you beat Usain Bolt out of the Blocks?","New York Times","interactives","http://www.nytimes.com/interactive/2016/08/13/sports/olympics/can-you-beat-usain-bolt-out-of-the-blocks.html","ENGELLI",[]],
["Spot the Ball","New York Times","interactives","http://projects.nytimes.com/interactive/sports/worldcup/spot-the-ball/2014/06/17","CANLI",[]],
["You Draw It","New York Times","interactives","http://www.nytimes.com/interactive/2015/05/28/upshot/you-draw-it-how-family-income-affects-childrens-college-chances.html","ENGELLI",[]],
["The Fallen of World War II","","interactives","http://www.fallen.io/ww2/","CANLI",["Three.js"]],
["Are you reflected in the new congress?","The Guardian","interactives","https://www.theguardian.com/us-news/ng-interactive/2014/nov/06/-sp-congress-diversity-women-race-lgbt-are-you-represented","CANLI",[]],
["Can you guess the voter turnout in your state?","The Guardian","interactives","https://www.theguardian.com/us-news/ng-interactive/2016/oct/11/voter-turnout-presidential-election-states-2012-2016","CANLI",[]],
["How well do you know your country?","The Guardian","interactives","https://www.theguardian.com/world/ng-interactive/2015/dec/02/how-well-do-you-really-know-your-country-take-our-quiz","CANLI",[]],
["Rio Run","The Guardian","interactives","http://riorun.theguardian.com","CANLI",[]],
["What do you call a person who moves to another country in search of a better life?","The Guardian","interactives","https://www.theguardian.com/uk-news/ng-interactive/2015/aug/28/words-migrant-refugee-immigration","CANLI",[]],
["Are you good enough to be a Tennis Line Judge?","Wall Street Journal","interactives","http://graphics.wsj.com/are-you-good-enough-to-be-a-tennis-line-judge/","CANLI",["Video.js"]],
["DNC Emoji Reactions","Washington Post","interactives","https://www.washingtonpost.com/graphics/politics/2016-election/dnc-emoji-reactions/","ENGELLI",[]],
["Billionaires","Bloomberg","visualizations","http://www.bloomberg.com/billionaires/2016-09-27/cya","ENGELLI",[]],
["How Red Meat Joined the 478 Other Things That Might Give You Cancer","Bloomberg","visualizations","http://www.bloomberg.com/graphics/2015-red-meat-cancer/","ENGELLI",[]],
["Dear Data","","visualizations","http://www.dear-data.com/","CANLI",[]],
["A visual history of women's Tennis","Financial Times","visualizations","https://ig.ft.com/sites/visual-history-of-womens-tennis/","CANLI",[]],
["Is urban cycling worth the risk?","Financial Times","visualizations","https://ig.ft.com/sites/urban-cycling/","CANLI",[]],
["Histography","","visualizations","http://histography.io/","CANLI",[]],
["Sizing up Sharks","National Geographic","visualizations","http://www.nationalgeographic.com/magazine/2016/06/shark-species-family-tree-ocean-ecosystem-predator/","CANLI",["D3.js"]],
["All Races on the same scale","New York Times","visualizations","http://www.nytimes.com/interactive/2016/08/20/sports/olympics/gold-medal-racing-speeds-on-the-same-scale.html","ENGELLI",[]],
["How could Trumps immigration Ban work?","New York Times","visualizations","http://www.nytimes.com/interactive/2016/07/22/us/politics/trump-immigration-ban-how-could-it-work.html","ENGELLI",[]],
["How Syrians are dying","New York Times","visualizations","http://www.nytimes.com/interactive/2015/09/14/world/middleeast/syria-war-deaths.html","ENGELLI",[]],
["How they got their guns","New York Times","visualizations","http://www.nytimes.com/interactive/2015/10/03/us/how-mass-shooters-got-their-guns.html","ENGELLI",[]],
["The 273 People, Places and Things Donald Trump Has Insulted on Twitter: A Complete List","New York Times","visualizations","http://www.nytimes.com/interactive/2016/01/28/upshot/donald-trump-twitter-insults.html","ENGELLI",[]],
["Visual History of Summer Olympics","New York Times","visualizations","http://www.nytimes.com/interactive/2016/08/08/sports/olympics/history-olympic-dominance-charts.html","ENGELLI",[]],
["The entire history of Kickstarter","Polygraph","visualizations","http://polygraph.cool/kickstarter/","CANLI",["D3.js"]],
["A visual intro to machine learning","R2D3","visualizations","http://www.r2d3.us/visual-intro-to-machine-learning-part-1/","ENGELLI",[]],
["Front Pages Analysis","South China Morning Post","visualizations","http://www.lucasinfografia.com/Front-pages-analysis","CANLI",[]],
["What's the world scared of?","The Guardian","visualizations","https://www.theguardian.com/news/datablog/ng-interactive/2015/jul/17/interactive-whats-the-world-scared-of","CANLI",[]],
["A decade of Trumps imports","Washington Post","visualizations","https://www.washingtonpost.com/graphics/politics/trump-products/","ENGELLI",[]],
["Most of Trump's charts skew the data","Washington Post","visualizations","https://www.washingtonpost.com/graphics/politics/2016-election/trump-charts/","ENGELLI",[]],
["Sizing up the Olympics","Washington Post","visualizations","https://www.washingtonpost.com/graphics/sports/olympics/scale-of-the-olympics/","ENGELLI",[]],
["The Depth of the Problem","Washington Post","visualizations","http://apps.washingtonpost.com/g/page/world/the-depth-of-the-problem/931/","ENGELLI",[]],
["Every active satellite orbiting earth","Quartz","visualizations","http://qz.com/296941/interactive-graphic-every-active-satellite-orbiting-earth/","CANLI",[]],
["Airbnb vs Berlin","","investigations","http://www.airbnbvsberlin.de/","CANLI",["D3.js","Carto"]],
["The Tennis Racket","Buzzfeed","investigations","https://www.buzzfeed.com/heidiblake/the-tennis-racket","CANLI",[]],
["A Plagiarism Scandal is unfolding in the Crossword world","FiveThirtyEight","investigations","http://fivethirtyeight.com/features/a-plagiarism-scandal-is-unfolding-in-the-crossword-world/","CANLI",[]],
["The Next to die","Marshall Project","investigations","https://www.themarshallproject.org/next-to-die","CANLI",["Three.js"]],
["How the nominees' convention speeches compare","New York Times","investigations","http://www.nytimes.com/interactive/2016/07/29/us/elections/trump-clinton-pence-kaine-speeches.html","ENGELLI",[]],
["Machine Bias","ProPublica","investigations","https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing","CANLI",[]],
["What Facebook knows about you","ProPublica","investigations","https://www.propublica.org/article/breaking-the-black-box-what-facebook-knows-about-you","CANLI",[]],
["The Panama Papers","SZ","investigations","http://panamapapers.sueddeutsche.de/","CANLI",["Chart.js"]],
["The Counted","The Guardian","investigations","https://www.theguardian.com/us-news/ng-interactive/2015/jun/01/the-counted-police-killings-us-database","CANLI",[]],
["The Android Administration","The Intercept","investigations","https://theintercept.com/2016/04/22/googles-remarkably-close-relationship-with-the-obama-white-house-in-two-charts/","CANLI",[]],
["A visual history of Donald Trump dominating the news cycle","Washington Post","investigations","https://www.washingtonpost.com/graphics/politics/donald-trump-vs-hillary-clinton-in-media/","ENGELLI",[]],
["Fatal Force","Washington Post","investigations","https://www.washingtonpost.com/graphics/national/police-shootings-2016/","ENGELLI",[]],
["Das sind Deutschlands grünste Großstädte","Berliner Morgenpost","drone","http://interaktiv.morgenpost.de/gruenste-staedte-deutschlands/","CANLI",["Leaflet"]],
["Greenland is melting away","New York Times","drone","http://www.nytimes.com/interactive/2015/10/27/world/greenland-is-melting-away.html","ENGELLI",[]],
["Living in China's Expanding Deserts","New York Times","drone","http://www.nytimes.com/interactive/2016/10/24/world/asia/living-in-chinas-expanding-deserts.html","ENGELLI",[]],
["What China has been building in the South China Sea","New York Times","drone","http://www.nytimes.com/interactive/2015/07/30/world/asia/what-china-has-been-building-in-the-south-china-sea-2016.html","ENGELLI",[]],
["Las Vegas Growth Map","ProPublica","drone","https://projects.propublica.org/las-vegas-growth-map/","CANLI",[]],
["Losing Ground","ProPublica","drone","https://projects.propublica.org/louisiana/","CANLI",[]],
["Corals, South China Sea","The Guardian","drone","https://www.theguardian.com/world/ng-interactive/2015/sep/17/south-china-sea-images-reveal-impact-on-coral-of-beijings-military-bases","CANLI",[]],
["AP Interactive","","portfolios","https://twitter.com/AP_Interactive","CANLI",[]],
["Berliner Morgenpost","","portfolios","http://www.morgenpost.de/interaktiv/","CANLI",[]],
["Bloomberg","","portfolios","https://www.bloomberg.com/graphics/infographics/","ENGELLI",[]],
["BuzzFeedNews","","portfolios","https://github.com/BuzzFeedNews/everything","CANLI",[]],
["Datasketch.es","","portfolios","http://www.datasketch.es/","CANLI",[]],
["FiveThirtyEight","","portfolios","https://twitter.com/FiveThirtyEight","CANLI",[]],
["Guardian Visuals","","portfolios","https://twitter.com/GuardianVisuals","CANLI",[]],
["Graphics Departments Twitter List (collection)","","portfolios","https://twitter.com/archietse/lists/graphics-departments","CANLI",[]],
["Interactive Things","","portfolios","https://twitter.com/IXT","CANLI",[]],
["Kiln","","portfolios","https://twitter.com/k_i_l_n","CANLI",[]],
["New York Times interactive Projects 2013","","portfolios","http://www.nytimes.com/newsgraphics/2013/12/30/year-in-interactive-storytelling/","CANLI",[]],
["New York Times interactive Projects 2014","","portfolios","http://www.nytimes.com/interactive/2014/12/29/us/year-in-interactive-storytelling.html","ENGELLI",[]],
["New York Times interactive Projects 2015","","portfolios","http://www.nytimes.com/interactive/2015/us/year-in-interactive-storytelling.html","ENGELLI",[]],
["NZZ Storytelling","","portfolios","https://twitter.com/NZZStorytelling","CANLI",[]],
["Polygraph","","portfolios","http://polygraph.cool/","CANLI",[]],
["ProPublica","","portfolios","https://www.propublica.org/data/","CANLI",[]],
["SRF Data","","portfolios","http://www.srf.ch/data","CANLI",[]],
["Tulp Interactive","","portfolios","http://tulpinteractive.com/","CANLI",[]],
["Washington Post Graphics","","portfolios","https://twitter.com/PostGraphics","CANLI",[]],
["Webkid","","portfolios","http://webkid.io/","CANLI",[]],
["Zeit Online","","portfolios","http://zeit.de/datenjournalismus","CANLI",[]]
];

const PROJECTS = PROJECTS_RAW.map((r,i)=>({
  i, title:r[0], outlet:r[1], sec:r[2], url:r[3], live:r[4], tech:r[5]
}));
