const projects=[
{title:"Flamingoların İzinde",team:"Ceyda Gündoğan",category:"ekoloji",label:"Kent ekolojisi",color:"#ff8ca3",cover:"assets/covers/flamingolarin-izinde-2-pptx.png",website:"https://www.flamingolarınizinde.com/",instagram:"https://www.instagram.com/flamingolarinizinde",description:"Gediz Deltası’nın ekolojik döngüsünü flamingolar üzerinden anlatıyor; bilimsel bilgiyi saha çekimleri, uzman görüşleri ve duygusal bir dijital anlatıyla buluşturuyor.",tags:["Gediz Deltası","91 kişilik anket","Videocast"]},
{title:"Kentte Söz Hakkı",team:"Simay Gençay · Selin Sapanlı",category:"kent",label:"Genç katılımı",color:"#ff654f",cover:"assets/covers/kentte-soz-hakki.png",website:"https://simayselin.github.io/kenttesozhakki.github.io/index.html",instagram:"https://www.instagram.com/kenttesozhakki",youtube:"https://youtube.com/@kenttesozhakki",description:"İzmirli gençlerin Kent Konseyi’ni tanımasını ve ilgi alanlarına uygun çalışma grubunu etkileşimli bir testle keşfetmesini sağlayan çok platformlu proje.",tags:["İzmir Kent Konseyi","Üyelik testi","Çok platformlu"]},
{title:"Kentin Görünmez Sınırları",team:"Ayça Güngör",category:"kent",label:"Güvenli kent",color:"#a78bfa",cover:"assets/covers/kentin-gorunmez-sinirlari.png",website:"https://aycaaguungor-creator.github.io/aycaagungor.github.io/",instagram:"https://www.instagram.com/kentin_gorunmez_sinirlari",youtube:"https://www.youtube.com/@kenting%C3%B6r%C3%BCnmezs%C4%B1n%C4%B1rlar%C4%B1",description:"Kadınlar ve LGBTİ+ bireylerin fiziksel ve duygusal güvenlik deneyimlerini katılımcı haritalama yoluyla kolektif bir görünürlük alanına taşıyor.",tags:["Katılımcı harita","Odak grup","Belgesel"]},
{title:"İki Dünyayı Taşımak",team:"Selin Öncü",category:"toplum",label:"Hak temelli dayanışma",color:"#f3a85d",cover:"assets/covers/iki-dunyayi-tasimak.png",website:"https://selinoncu.github.io/",instagram:"https://www.instagram.com/ikidunyayitasimak",youtube:"http://www.youtube.com/@%C4%B0kiD%C3%BCnyay%C4%B1Ta%C5%9F%C4%B1mak",description:"Engelli çocuğu olan ebeveynlerin görünmeyen bakım emeğini ve bakım veren kimliğinin ardında kalan bireysel yaşamlarını hak temelli dayanışma yaklaşımıyla ele alıyor.",tags:["Görünmeyen emek","Saha araştırması","Hak temelli iletişim"]},
{title:"Algoritmik Cinsiyet",team:"Simten Karaosmanoğlu",category:"medya",label:"Dijital kültür",color:"#49e1de",cover:"assets/covers/finalsunum.png",website:"https://simtenkaraosmanoglu.github.io/",instagram:"https://www.instagram.com/algoritmikcinsiyet",youtube:"https://youtube.com/@algoritmikcinsiyet",description:"Kısa video platformlarında toplumsal cinsiyet temsillerini ve algoritmaların genç yetişkinlerin algısı üzerindeki rolünü görünür kılıyor.",tags:["108 kişilik anket","Cultural jamming","TikTok simülasyonu"]},
{title:"Sağlığın Kalkanı",team:"Helin Tecim",category:"toplum",label:"Sağlık iletişimi",color:"#6cc5ff",cover:"assets/covers/sa-l-n-kalkan-final-sunum.png",website:"https://helintecim.github.io/index.html",instagram:"https://www.instagram.com/sagligin_kalkani/",youtube:"https://www.youtube.com/@Sa%C4%9Fl%C4%B1%C4%9F%C4%B1nKalkan%C4%B1",description:"HPV aşısı etrafındaki bilgi kirliliği ve damgalanmayı, korku yerine korunma ve güven üzerinden yeniden çerçeveliyor.",tags:["HPV aşısı","Uzman görüşü","Podcast"]},
{title:"Solu-Can",team:"Seray Çalışkan · Leo Kayra Fletcher",category:"ekoloji",label:"Döngüsel yaşam",color:"#80b96e",cover:"assets/covers/sunum-leo-ve-seray.png",website:"https://evimdekidoga.com/",instagram:"https://www.instagram.com/evimdekidoga/",description:"Evde kompost üretimini uzman anlatısı, uygulamalı video ve samimi bir görsel kimlikle erişilebilir hale getiren ekolojik iletişim projesi.",tags:["Kompost 101","Videocast","Sürdürülebilirlik"]},
{title:"Görmenin Ötesinde İzmir",team:"Elif Şahin · İrem Ceylin Demircan",category:"erisim",label:"Erişilebilir kent",color:"#f8ea44",cover:"assets/covers/final-sunum.png",description:"Görme engelli gençlerin kentte ve dijital alanda yaşadığı belirsizlik, kontrol kaybı ve güvensizliği deneyimsel bir web anlatısına dönüştürüyor.",tags:["Deneyim haritası","Belgesel","Erişilebilirlik"]},
{title:"VİZİ",team:"Eren Oral · Togay Yalçın Özkaya",category:"erisim",label:"Erişilebilir ulaşım",color:"#f4ff37",cover:"assets/covers/vizi.png",website:"https://www.vizi.com.tr/",youtube:"https://www.youtube.com/@gorunmeyenigoster3526",description:"İzmir’de engelli bireylerin ulaşımda karşılaştığı bilgi bariyerine gerçek zamanlı arıza takibi, erişilebilir rota bilgisi ve veri temelli savunuculukla yanıt veriyor.",tags:["120 kişilik saha analizi","PWA","Gerçek zamanlı harita"]}
];
const grid=document.querySelector('#project-grid'),dialog=document.querySelector('#project-dialog'),content=document.querySelector('#dialog-content'),closeButton=document.querySelector('.dialog-close');
function channelLinks(p,compact=false){const links=`${p.website?`<a href="${p.website}" target="_blank" rel="noopener" aria-label="${p.title} web sitesi">Web <span>↗</span></a>`:''}${p.instagram?`<a href="${p.instagram}" target="_blank" rel="noopener" aria-label="${p.title} Instagram hesabı">Instagram <span>↗</span></a>`:''}${p.youtube?`<a href="${p.youtube}" target="_blank" rel="noopener" aria-label="${p.title} YouTube kanalı">YouTube <span>↗</span></a>`:''}`;return links?`<div class="channel-links${compact?' compact':''}">${links}</div>`:''}
function render(filter='all'){const visible=projects.filter(p=>filter==='all'||p.category===filter);document.querySelector('#visible-count').textContent=visible.length;grid.innerHTML=visible.map(p=>`<article class="project-card" tabindex="0" role="button" aria-label="${p.title} projesini aç" data-title="${p.title}" style="--card-color:${p.color}"><div class="card-media">${p.cover?`<img src="${p.cover}" alt="${p.title} proje görseli" loading="lazy">`:`<div class="card-fallback">${p.title}</div>`}<span class="card-index">${String(projects.indexOf(p)+1).padStart(2,'0')}</span><span class="card-label">${p.label}</span></div><div class="card-meta"><div><h3>${p.title}</h3><p>${p.team}</p></div><span class="card-arrow">↗</span></div>${channelLinks(p,true)}</article>`).join('');grid.querySelectorAll('.project-card').forEach(card=>{const open=()=>openProject(projects.find(p=>p.title===card.dataset.title));card.addEventListener('click',open);card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a')){e.preventDefault();open()}});card.querySelectorAll('a').forEach(link=>link.addEventListener('click',e=>e.stopPropagation()))})}
function openProject(p){const actions=channelLinks(p);content.innerHTML=`<div class="dialog-hero" style="--dialog-color:${p.color}">${p.cover?`<img src="${p.cover}" alt="">`:''}<h2 id="dialog-title">${p.title}</h2></div><div class="dialog-body"><div class="dialog-info"><span>Proje ekibi</span>${p.team}<span>Tema</span>${p.label}${actions||`<p class="site-pending">Proje bağlantıları henüz paylaşılmadı</p>`}</div><div><p class="dialog-description">${p.description}</p><div class="dialog-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></div>`;dialog.showModal()}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');render(button.dataset.filter)}));closeButton.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
